import { Language } from './types';

export const translations: Record<Language, any> = {
  fr: {
    nav: { home: 'Accueil', about: 'Vision', vision: 'Politique', realisations: 'Réalisations', ambassador: 'Ambassade', contact: 'Contacter' },
    hero: { subtitle: 'Jeune Leader & Économiste', title: "Max Jhonsley Gaspard", desc: "Max Johnsley Gaspard est un jeune leader haïtien, économiste, conférencier et militant socialiste, né le 19 janvier 2001 à Anse-Rouge (Artibonite). En janvier 2026, il est particulièrement actif en tant que figure émergente de la jeunesse haïtienne engagée. Voici les points clés de son parcours : Formation et Compétences : Polyglotte vivant actuellement en Chine, il utilise ses compétences linguistiques, notamment le mandarin, pour plaider en faveur d'une coopération sino-haïtienne.\n\n\nEngagement Politique : Il se définit comme un acteur politique engagé, critiquant ouvertement les autorités haïtiennes sur des sujets tels que l'abandon du système éducatif et les disparités sociales. Rôles Actuels : En janvier 2026, il a été nommé Ambassadeur de l'Univers des Livres en Chine, une mission visant à promouvoir la littérature et la culture. Gaspard est souvent présenté dans les médias sociaux haïtiens comme un \"jeune leader déterminé à transformer Haïti\" par le biais d'initiatives.", cta1: 'Sa Vision', cta2: 'Sa Ligne Politique', badge1: 'Polyglotte (Mandarin)', badge2: 'Ambassadeur Culturel', readMore: 'Voir plus', readLess: 'Voir moins' },
    about: { title: 'Explorer sa vision', p1: "La vision de Max Johnsley Gaspard pour la jeunesse haïtienne, telle qu'il la formule en ce début d'année 2026, repose sur l'idée que les jeunes doivent être les moteurs du changement radical et de la souveraineté diplomatique du pays.", p2: "Sa vision s'articule autour de quatre piliers majeurs : L'Éducation comme arme de libération : Gaspard dénonce vigoureusement l'abandon du système éducatif par les autorités. Pour lui, la jeunesse ne peut s'émanciper sans un accès à une éducation de qualité qui permettrait de rompre avec le cycle de la pauvreté et de l'instabilité politique. L'ouverture internationale et linguistique : En tant que leader polyglotte basé en Chine, il encourage les jeunes Haïtiens à maîtriser des outils de communication mondiaux, comme le mandarin, pour créer de nouveaux ponts diplomatiques. Il voit dans la coopération sino-haïtienne une opportunité unique pour la jeunesse de bénéficier de transferts de compétences et de bourses d'études. Engagement politique et socialisme : Il exhorte la jeunesse à s'impliquer directement dans la vie politique pour porter des idéaux socialistes. Sa vision rejette le statu quo des élites traditionnelles et prône une jeunesse active, capable de proposer des initiatives en faveur du développement durable. Paix et Réconciliation : Dans ses interventions récentes, notamment début 2025 et 2026, il appelle à la réconciliation dans les quartiers populaires (les ghettos). Il considère que la paix sociale est un préalable indispensable pour que la jeunesse puisse enfin jouer son rôle de leader dans la transformation nationale. En résumé, pour Max Johnsley Gaspard, la jeunesse haïtienne ne doit plus être une spectatrice de la crise, mais une force formée, politisée et ouverte sur le monde, capable de redéfinir l'avenir d'Haïti.", stats: { origin: 'Origine', birth: 'Naissance', residence: 'Lieu de vie', lang: 'Mandarin' }, cards: { economy: 'Économie & Militantisme', diplomacy: 'Diplomatie de la Jeunesse', speaker: 'Conférencier Inspirant' } },
    vision: { title: 'Sa Ligne Politique', pillars: [{ t: "Rapprochement Sino-Haïtien", d: "C'est le pilier de son discours actuel. Il prône activement une coopération bilatérale renforcée avec la République populaire de Chine, qu'il voit comme un partenaire stratégique capable d'offrir des alternatives aux alliances traditionnelles d'Haïti." }, { t: "Socialisme et Réforme Sociale", d: "Se définissant comme un jeune leader socialiste, il milite pour une réduction des disparités sociales et une meilleure répartition des richesses nationales." }, { t: "Éducation comme Priorité Nationale", d: "Il critique vivement l'abandon du système éducatif par les autorités actuelles. Sa politique repose sur l'idée que l'éducation est le moteur indispensable du développement et de la stabilité politique." }, { t: "Opposition aux Élites Traditionnelles", d: "Il se positionne comme une voix critique envers la classe politique établie, dénonçant l'instabilité chronique et l'incapacité des dirigeants à répondre aux besoins fondamentaux de la population." }, { t: "Diplomatie Culturelle", d: "À travers son rôle d'Ambassadeur de l'Univers des Livres, il utilise la culture et la littérature comme outils d'influence politique pour redorer l'image d'Haïti à l'international." }] },
    ambassador: { subtitle: 'Janvier 2026 - Nouveau Chapitre', title: "Ambassadeur de l'Univers des Livres en Chine", desc: "Max a été nommé Ambassadeur pour promouvoir la littérature et les échanges culturels.", support: "Une mission soutenue par des milliers de jeunes lecteurs." },
    footer: { mission: "Économiste et leader engagé, Max travaille sans relâche pour jeter des ponts entre Haïti et le reste du monde.", contact: "Contact", location: "Chine / Haïti", stayConnected: "Restez Connecté", rights: "Tous droits réservés." },
    contact: { title: 'Me Contacter', firstName: 'Prénom', lastName: 'Nom', email: 'Email', message: 'Message', submit: 'Envoyer', success: 'Message envoyé avec succès!', error: 'Erreur lors de l\'envoi du message. Veuillez réessayer.' }
  },

  en: {
    nav: { home: 'Home', about: 'Vision', vision: 'Politics', realisations: 'Achievements', ambassador: 'Ambassadorship', contact: 'Contact' },
    hero: { subtitle: 'Young Leader & Economist', title: "Max Jhonsley Gaspard", desc: "Max Johnsley Gaspard is a young Haitian leader, economist, speaker and socialist activist, born January 19, 2001, in Anse-Rouge (Artibonite). In January 2026, he is particularly active as an emerging figure of engaged Haitian youth. Here are the key points of his journey: Education and Skills: A polyglot currently living in China, he uses his linguistic skills, including Mandarin, to advocate for sino-Haitian cooperation.\n\n\nPolitical Engagement: He defines himself as an engaged political actor, openly criticizing Haitian authorities on issues such as the abandonment of the education system and social disparities. Current Roles: In January 2026, he was appointed Ambassador of the World of Books in China, a mission aimed at promoting literature and culture. Gaspard is often presented in Haitian social media as a \"young leader determined to transform Haiti\" through initiatives.", cta1: 'His Vision', cta2: 'His Political Line', badge1: 'Polyglot (Mandarin)', badge2: 'Cultural Ambassador', readMore: 'Read More', readLess: 'Read Less' },
    about: { title: 'Exploring His Vision', p1: "Max Johnsley Gaspard's vision for Haitian youth, as he articulates at the beginning of 2026, is based on the idea that young people must be the driving force behind radical change and diplomatic sovereignty in the country.", p2: "His vision is structured around four major pillars: Education as a tool of liberation: Gaspard vigorously denounces the abandonment of the educational system by the authorities. For him, young people cannot emancipate themselves without access to quality education that would allow them to break the cycle of poverty and political instability. International and linguistic openness: As a multilingual leader based in China, he encourages young Haitians to master global communication tools, such as Mandarin, to create new diplomatic bridges. He sees in Sino-Haitian cooperation a unique opportunity for young people to benefit from skills transfers and scholarships. Political engagement and socialism: He urges youth to directly involve themselves in political life to promote socialist ideals. His vision rejects the status quo of traditional elites and advocates for an active youth capable of proposing initiatives in favor of sustainable development. Peace and Reconciliation: In his recent interventions, notably in early 2025 and 2026, he calls for reconciliation in popular neighborhoods (the ghettos). He considers social peace an essential prerequisite for young people to finally play their role as leaders in national transformation. In summary, for Max Johnsley Gaspard, Haitian youth should no longer be spectators of the crisis, but a formed, politicized, and globally-minded force capable of redefining Haiti's future.", stats: { origin: 'Origin', birth: 'Birth', residence: 'Living in', lang: 'Mandarin' }, cards: { economy: 'Economy & Activism', diplomacy: 'Youth Diplomacy', speaker: 'Inspiring Speaker' } },
    vision: { title: 'His Political Line', pillars: [{ t: "Sino-Haitian Rapprochement", d: "It is the cornerstone of his current speech. He actively advocates for enhanced bilateral cooperation with the People's Republic of China, which he sees as a strategic partner capable of offering alternatives to Haiti's traditional alliances." }, { t: "Socialism and Social Reform", d: "Defining himself as a young socialist leader, he campaigns for a reduction in social disparities and better distribution of national wealth." }, { t: "Education as National Priority", d: "He harshly criticizes the abandonment of the educational system by current authorities. His policy is based on the idea that education is the essential driver of development and political stability." }, { t: "Opposition to Traditional Elites", d: "He positions himself as a critical voice against the established political class, denouncing chronic instability and leaders' inability to meet the population's fundamental needs." }, { t: "Cultural Diplomacy", d: "Through his role as Ambassador of the World of Books, he uses culture and literature as political influence tools to restore Haiti's image internationally." }] },
    ambassador: { subtitle: 'January 2026 - New Chapter', title: "Ambassador of the Universe of Books in China", desc: "Max was appointed Ambassador to promote literature and cultural exchange.", support: "A mission supported by thousands of young readers." },
    footer: { mission: "Economist and committed leader, Max works tirelessly to build bridges between Haiti and the world.", contact: "Contact", location: "China / Haiti", stayConnected: "Stay Connected", rights: "All rights reserved." },
    contact: { title: 'Contact Me', firstName: 'First Name', lastName: 'Last Name', email: 'Email', message: 'Message', submit: 'Send', success: 'Message sent successfully!', error: 'Error sending message. Please try again.' }
  },

  ru: {
    nav: { home: 'Главная', about: 'Видение', vision: 'Политика', realisations: 'Достижения', ambassador: 'Посол', contact: 'Контакты' },
    hero: { subtitle: 'Молодой лидер и экономист', title: "Max Jhonsley Gaspard", desc: "Макс Джонсли Гаспар — молодой гаитянский лидер, экономист, оратор и социалистический активист, родившийся 19 января 2001 года в Анс-Руж (Артибонит). В январе 2026 года он особенно активен как восходящая фигура ангажированной гаитянской молодежи. Вот ключевые моменты его пути: Образование и навыки: Полиглот, в настоящее время живущий в Китае, он использует свои языковые навыки, включая мандаринский, для содействия китайско-гаитянскому сотрудничеству.\n\nПолитическое участие: Он определяет себя как приверженного политического деятеля, открыто критикующего гаитянские власти по таким вопросам, как упадок образовательной системы и социальное неравенство. Текущие роли: В январе 2026 года он был назначен Послом Вселенной Книг в Китае, миссия которой направлена на продвижение литературы и культуры. Гаспар часто представляется в гаитянских социальных сетях как \"молодой лидер, решительно настроенный трансформировать Гаити\" через инициативы.", cta1: 'Его видение', cta2: 'Его политическая линия', badge1: 'Полиглот (Мандарин)', badge2: 'Посол культуры', readMore: 'Читать далее', readLess: 'Скрыть' },
    about: { title: 'Исследуя свое видение', p1: "Видение Макса Джонсли Гаспарда для молодежи Гаити, как он формулирует в начале 2026 года, основывается на идее, что молодые люди должны быть движущей силой радикальных изменений и дипломатического суверенитета страны.", p2: "Его видение структурировано вокруг четырех основных столпов: Образование как инструмент освобождения: Гаспард энергично осуждает заброшенность образовательной системы властями. По его мнению, молодежь не может освободиться без доступа к качественному образованию, которое позволило бы прервать цикл бедности и политической нестабильности. Международное и языковое открытие: Как полиглот-лидер, базирующийся в Китае, он поощряет молодых гаитян овладевать глобальными средствами коммуникации, такими как мандарин, для создания новых дипломатических мостов. Он видит в сино-гаитянском сотрудничестве уникальную возможность для молодежи получить передачу навыков и стипендии. Политическое участие и социализм: Он призывает молодежь напрямую включаться в политическую жизнь, чтобы продвигать социалистические идеалы. Его видение отвергает статус-кво традиционных элит и выступает за активную молодежь, способную предлагать инициативы в пользу устойчивого развития. Мир и примирение: В своих недавних выступлениях, особенно в начале 2025 и 2026 годов, он призывает к примирению в народных кварталах (трущобах). Он считает социальный мир необходимым условием для того, чтобы молодежь могла наконец сыграть свою роль лидеров в национальном преобразовании. В заключение, для Макса Джонсли Гаспарда, молодежь Гаити больше не должна быть зрителем кризиса, но сформированной, политизированной и ориентированной на мир силой, способной переопределить будущее Гаити.", stats: { origin: 'Происхождение', birth: 'Рождение', residence: 'Проживание', lang: 'Мандарин' }, cards: { economy: 'Экономика и активизм', diplomacy: 'Молодежная дипломатия', speaker: 'Вдохновляющий спикер' } },
    vision: { title: 'Его политическая линия', pillars: [{ t: "Сближение Китая и Гаити", d: "Это краеугольный камень его текущей речи. Он активно выступает за усиление двустороннего сотрудничества с Китайской Народной Республикой, которую он видит как стратегического партнера, способного предложить альтернативы традиционным союзникам Гаити." }, { t: "Социализм и социальные реформы", d: "Определяя себя как молодого социалистического лидера, он борется за снижение социального неравенства и лучшее распределение национального богатства." }, { t: "Образование как национальный приоритет", d: "Он жестко критикует бросание образовательной системы действующими властями. Его политика основана на идее о том, что образование является важнейшим двигателем развития и политической стабильности." }, { t: "Противостояние традиционной элите", d: "Он позиционирует себя как критический голос против устоявшегося политического класса, осуждающего хроническую нестабильность и неспособность лидеров удовлетворять основные потребности населения." }, { t: "Культурная дипломатия", d: "Через свою роль Посла Мира книг он использует культуру и литературу как инструменты политического влияния для восстановления международного имиджа Гаити." }] },
    ambassador: { subtitle: 'Январь 2026 - Новая глава', title: "Посол Вселенной Книг в Китае", desc: "Макс был назначен послом для продвижения литературы и культурного обмена.", support: "Миссия, поддерживаемая тысячами молодых читателей." },
    footer: { mission: "Экономист и преданный лидер, Макс неустанно работает над наведением мостов между Гаити и миром.", contact: "Контакт", location: "Китай / Гаити", stayConnected: "Оставайтесь на связи", rights: "Все права защищены." },
    contact: { title: 'Связаться со мной', firstName: 'Имя', lastName: 'Фамилия', email: 'Email', message: 'Сообщение', submit: 'Отправить', success: 'Сообщение успешно отправлено!', error: 'Ошибка при отправке сообщения. Пожалуйста, попробуйте еще раз.' }
  },

  zh: {
    nav: { home: '首页', about: '愿景', vision: '政治', realisations: '成就', ambassador: '大使', contact: '联系' },
    hero: { subtitle: '年轻领袖 & 经济学家', title: "Max Jhonsley Gaspard", desc: "Max Johnsley Gaspard 是一位年轻的海地领袖、经济学家、演讲者和社会主义活动家，2001年1月19日出生于安斯鲁日（阿蒂博尼特）。在2026年1月，他作为参与海地青年的新兴人物特别活跃。以下是他旅程的关键点：教育与技能：目前居住在中国的多语言者，他利用包括普通话在内的语言技能，倡导中-海地合作。\n\n政治参与：他定义自己为参与政治的行动者，公开批评海地当局在教育系统被遗弃和社会差异等问题上。当前角色：2026年1月，他被任命为中国图书宇宙大使，旨在促进文学和文化。Gaspard 在海地社交媒体中常被描述为\"决心通过倡议改变海地\"的\"年轻领袖\"。", cta1: '他的愿景', cta2: '他的政治路线', badge1: '多语言者（普通话）', badge2: '文化大使', readMore: '查看更多', readLess: '收起' },
    about: { title: '探索他的愿景', p1: "Max Johnsley Gaspard 对海地青年的愿景，正如他在2026年初所阐述的，基于年轻人必须成为国家激进变革和外交主权的驱动力的理念。", p2: "他的愿景围绕四个主要支柱构建：教育作为解放工具：Gaspard 强烈谴责当局对教育系统的遗弃。对他来说，年轻人无法在没有获得优质教育的情况下解放自己，优质教育将使他们能够打破贫困和政治不稳定的循环。国际和语言开放：作为一位基于中国的多语言领袖，他鼓励年轻海地人掌握全球沟通工具，如普通话，以创建新的外交桥梁。他认为中-海地合作为年轻人提供了从技能转移和奖学金中受益的独特机会。政治参与和社会主义：他敦促青年直接参与政治生活，以促进社会主义理想。他的愿景拒绝传统精英的现状，倡导能够提出有利于可持续发展的倡议的积极青年。和平与和解：在他最近的干预中，特别是在2025年初和2026年初，他呼吁在平民区（贫民窟）进行和解。他认为社会和平是年轻人最终在国家转型中发挥领导作用的必要前提。总之，对于 Max Johnsley Gaspard 来说，海地青年不应再是危机的旁观者，而应是一支经过培训、政治化且具有全球视野的力量，能够重新定义海地的未来。", stats: { origin: '起源', birth: '出生', residence: '居住地', lang: '普通话' }, cards: { economy: '经济与行动主义', diplomacy: '青年外交', speaker: '鼓舞人心的演讲者' } },
    vision: { title: '他的政治路线', pillars: [{ t: "中-海地接近", d: "这是他当前演讲的基石。他积极倡导加强与中华人民共和国之间的双边合作，将其视为能够为海地传统联盟提供替代方案的战略伙伴。" }, { t: "社会主义与社会改革", d: "将自己定义为年轻的社会主义领袖，他致力于减少社会差异和更好地分配国家财富。" }, { t: "教育作为国家优先事项", d: "他严厉批评当前当局对教育系统的遗弃。他的政策基于教育是发展和政治稳定不可或缺的驱动力的理念。" }, { t: "反对传统精英", d: "他定位自己为反对既定政治阶层的批评声音，谴责长期不稳定和领导人无法满足人民基本需求。" }, { t: "文化外交", d: "通过他作为图书宇宙大使的角色，他利用文化和文学作为政治影响力工具，在国际上恢复海地的形象。" }] },
    ambassador: { subtitle: '2026年1月 - 新篇章', title: "中国图书宇宙大使", desc: "Max 被任命为大使，以促进文学和文化交流。", support: "一项得到数千名年轻读者支持的任务。" },
    footer: { mission: "经济学家和坚定的领袖，Max 不知疲倦地工作，为海地和世界之间搭建桥梁。", contact: "联系", location: "中国 / 海地", stayConnected: "保持联系", rights: "保留所有权利。" },
    contact: { title: '联系我', firstName: '名字', lastName: '姓氏', email: '邮箱', message: '消息', submit: '发送', success: '消息发送成功！', error: '发送消息时出错。请重试。' }
  }
};