
import { Language } from './types';

export const translations: Record<Language, any> = {
  fr: {
    nav: { home: 'Accueil', about: 'Parcours', vision: 'Vision', realisations: 'Réalisations', ambassador: 'Ambassade', contact: 'Contacter' },
    hero: { subtitle: 'Jeune Leader & Économiste', title: "Max Jhonsley Gaspard", desc: "Max Johnsley Gaspard est un jeune leader haïtien, économiste, conférencier et militant socialiste, né le 19 janvier 2001 à Anse-Rouge (Artibonite). En janvier 2026, il est particulièrement actif en tant que figure émergente de la jeunesse haïtienne engagée. Voici les points clés de son parcours : Formation et Compétences : Polyglotte vivant actuellement en Chine, il utilise ses compétences linguistiques, notamment le mandarin, pour plaider en faveur d'une coopération sino-haïtienne.\n\n\nEngagement Politique : Il se définit comme un acteur politique engagé, critiquant ouvertement les autorités haïtiennes sur des sujets tels que l'abandon du système éducatif et les disparités sociales. Rôles Actuels : En janvier 2026, il a été nommé Ambassadeur de l'Univers des Livres en Chine, une mission visant à promouvoir la littérature et la culture. Gaspard est souvent présenté dans les médias sociaux haïtiens comme un \"jeune leader déterminé à transformer Haïti\" par le biais d'initiatives.", cta1: 'Sa Vision', cta2: 'Sa Ligne Politique', badge1: 'Polyglotte (Mandarin)', badge2: 'Ambassadeur Culturel', readMore: 'Voir plus', readLess: 'Voir moins' },
    about: { title: 'Un Parcours sans Frontières', p1: "Né le 19 janvier 2001 à Anse-Rouge, Max Johnsley Gaspard s'est forgé un destin international tout en restant profondément ancré dans ses racines haïtiennes.", p2: "Aujourd'hui basé en Chine, il utilise sa maîtrise du Mandarin et son expertise en économie pour construire des ponts stratégiques.", stats: { origin: 'Origine', birth: 'Naissance', residence: 'Lieu de vie', lang: 'Mandarin' }, cards: { economy: 'Économie & Militantisme', diplomacy: 'Diplomatie de la Jeunesse', speaker: 'Conférencier Inspirant' } },
    vision: { title: 'Sa Ligne Politique', pillars: [{ t: "Rapprochement Sino-Haïtien", d: "C'est le pilier de son discours actuel. Il prône activement une coopération bilatérale renforcée avec la République populaire de Chine, qu'il voit comme un partenaire stratégique capable d'offrir des alternatives aux alliances traditionnelles d'Haïti." }, { t: "Socialisme et Réforme Sociale", d: "Se définissant comme un jeune leader socialiste, il milite pour une réduction des disparités sociales et une meilleure répartition des richesses nationales." }, { t: "Éducation comme Priorité Nationale", d: "Il critique vivement l'abandon du système éducatif par les autorités actuelles. Sa politique repose sur l'idée que l'éducation est le moteur indispensable du développement et de la stabilité politique." }, { t: "Opposition aux Élites Traditionnelles", d: "Il se positionne comme une voix critique envers la classe politique établie, dénonçant l'instabilité chronique et l'incapacité des dirigeants à répondre aux besoins fondamentaux de la population." }, { t: "Diplomatie Culturelle", d: "À travers son rôle d'Ambassadeur de l'Univers des Livres, il utilise la culture et la littérature comme outils d'influence politique pour redorer l'image d'Haïti à l'international." }] },
    ambassador: { subtitle: 'Janvier 2026 - Nouveau Chapitre', title: "Ambassadeur de l'Univers des Livres en Chine", desc: "Max a été nommé Ambassadeur pour promouvoir la littérature et les échanges culturels.", support: "Une mission soutenue par des milliers de jeunes lecteurs." },
    footer: { mission: "Économiste et leader engagé, Max travaille sans relâche pour jeter des ponts entre Haïti et le reste du monde.", contact: "Contact", location: "Chine / Haïti (Artibonite)", stayConnected: "Restez Connecté", rights: "Tous droits réservés." },
    contact: { title: 'Me Contacter', firstName: 'Prénom', lastName: 'Nom', email: 'Email', message: 'Message', submit: 'Envoyer', success: 'Message envoyé avec succès!', error: 'Erreur lors de l\'envoi du message. Veuillez réessayer.' }
  },
  en: {
      nav: { home: 'Home', about: 'Journey', vision: 'Vision', realisations: 'Achievements', ambassador: 'Ambassadorship', contact: 'Contact' },
      hero: { subtitle: 'Young Leader & Economist', title: "Max Jhonsley Gaspard", desc: "Max Johnsley Gaspard is a young Haitian leader, economist, speaker and socialist activist, born January 19, 2001, in Anse-Rouge (Artibonite). In January 2026, he is particularly active as an emerging figure of engaged Haitian youth. Here are the key points of his journey: Education and Skills: A polyglot currently living in China, he uses his linguistic skills, including Mandarin, to advocate for sino-Haitian cooperation.\n\n\nPolitical Engagement: He defines himself as an engaged political actor, openly criticizing Haitian authorities on issues such as the abandonment of the education system and social disparities. Current Roles: In January 2026, he was appointed Ambassador of the World of Books in China, a mission aimed at promoting literature and culture. Gaspard is often presented in Haitian social media as a \"young leader determined to transform Haiti\" through initiatives.", cta1: 'His Vision', cta2: 'His Political Line', badge1: 'Polyglot (Mandarin)', badge2: 'Cultural Ambassador', readMore: 'Read More', readLess: 'Read Less' },
    about: { title: 'A Journey without Borders', p1: "Born on January 19, 2001 in Anse-Rouge, Max Johnsley Gaspard has forged an international destiny while remaining deeply rooted in his Haitian origins.", p2: "Now based in China, he uses his mastery of Mandarin and his expertise in economics to build strategic bridges.", stats: { origin: 'Origin', birth: 'Birth', residence: 'Living in', lang: 'Mandarin' }, cards: { economy: 'Economy & Activism', diplomacy: 'Youth Diplomacy', speaker: 'Inspiring Speaker' } },
    vision: { title: 'His Political Line', pillars: [{ t: "Sino-Haitian Rapprochement", d: "It is the cornerstone of his current speech. He actively advocates for enhanced bilateral cooperation with the People's Republic of China, which he sees as a strategic partner capable of offering alternatives to Haiti's traditional alliances." }, { t: "Socialism and Social Reform", d: "Defining himself as a young socialist leader, he campaigns for a reduction in social disparities and better distribution of national wealth." }, { t: "Education as National Priority", d: "He harshly criticizes the abandonment of the educational system by current authorities. His policy is based on the idea that education is the essential driver of development and political stability." }, { t: "Opposition to Traditional Elites", d: "He positions himself as a critical voice against the established political class, denouncing chronic instability and leaders' inability to meet the population's fundamental needs." }, { t: "Cultural Diplomacy", d: "Through his role as Ambassador of the World of Books, he uses culture and literature as political influence tools to restore Haiti's image internationally." }] },
    ambassador: { subtitle: 'January 2026 - New Chapter', title: "Ambassador of the Universe of Books in China", desc: "Max was appointed Ambassador to promote literature and cultural exchange.", support: "A mission supported by thousands of young readers." },
    footer: { mission: "Economist and committed leader, Max works tirelessly to build bridges between Haiti and the world.", contact: "Contact", location: "China / Haiti (Artibonite)", stayConnected: "Stay Connected", rights: "All rights reserved." },
    contact: { title: 'Contact Me', firstName: 'First Name', lastName: 'Last Name', email: 'Email', message: 'Message', submit: 'Send', success: 'Message sent successfully!', error: 'Error sending message. Please try again.' }
  },
  ru: {
    nav: { home: 'Главная', about: 'Путь', vision: 'Видение', realisations: 'Достижения', ambassador: 'Посол', contact: 'Контакты' },
hero: { subtitle: 'Молодой лидер и экономист', title: "Max Jhonsley Gaspard", desc: "Макс Джонсли Гаспар — молодой гаитянский лидер, экономист, оратор и социалистический активист, родившийся 19 января 2001 года в Анс-Руж (Артибонит). В январе 2026 года он особенно активен как восходящая фигура ангажированной гаитянской молодежи. Вот ключевые моменты его пути: Образование и навыки: Полиглот, в настоящее время живущий в Китае, он использует свои языковые навыки, включая мандаринский, для содействия китайско-гаитянскому сотрудничеству.\n\nПолитическое участие: Он определяет себя как приверженного политического деятеля, открыто критикующего гаитянские власти по таким вопросам, как упадок образовательной системы и социальное неравенство. Текущие роли: В январе 2026 года он был назначен Послом Вселенной Книг в Китае, миссия которой направлена на продвижение литературы и культуры. Гаспар часто представляется в гаитянских социальных сетях как \"молодой лидер, решительно настроенный трансформировать Гаити\" через инициативы.", cta1: 'Его видение', cta2: 'Его политическая линия', badge1: 'Полиглот (Мандарин)', badge2: 'Посол культуры', readMore: 'Читать далее', readLess: 'Скрыть' },
    about: { title: 'Путь без границ', p1: "Родившийся 19 января 2001 года в Анс-Руж, Макс Джонсли Гаспар выковал международную судьбу, оставаясь глубоко преданным своим гаитянским корням.", p2: "Сейчас он живет в Китае и использует знание мандаринского языка и опыт в экономике для наведения стратегических мостов.", stats: { origin: 'Происхождение', birth: 'Рождение', residence: 'Проживание', lang: 'Мандарин' }, cards: { economy: 'Экономика и активизм', diplomacy: 'Молодежная дипломатия', speaker: 'Вдохновляющий спикер' } },
    vision: { title: 'Его политическая линия', pillars: [{ t: "Сближение Китая и Гаити", d: "Это краеугольный камень его текущей речи. Он активно выступает за усиление двустороннего сотрудничества с Китайской Народной Республикой, которую он видит как стратегического партнера, способного предложить альтернативы традиционным союзникам Гаити." }, { t: "Социализм и социальные реформы", d: "Определяя себя как молодого социалистического лидера, он борется за снижение социального неравенства и лучшее распределение национального богатства." }, { t: "Образование как национальный приоритет", d: "Он жестко критикует бросание образовательной системы действующими властями. Его политика основана на идее о том, что образование является важнейшим двигателем развития и политической стабильности." }, { t: "Противостояние традиционной элите", d: "Он позиционирует себя как критический голос против устоявшегося политического класса, осуждающего хроническую нестабильность и неспособность лидеров удовлетворять основные потребности населения." }, { t: "Культурная дипломатия", d: "Через свою роль Посла Мира книг он использует культуру и литературу как инструменты политического влияния для восстановления международного имиджа Гаити." }] },
    ambassador: { subtitle: 'Январь 2026 - Новая глава', title: "Посол Вселенной Книг в Китае", desc: "Макс был назначен послом для продвижения литературы и культурного обмена.", support: "Миссия, поддерживаемая тысячами молодых читателей." },
    footer: { mission: "Экономист и преданный лидер, Макс неустанно работает над наведением мостов между Гаити и миром.", contact: "Контакт", location: "Китай / Гаити (Артибонит)", stayConnected: "Оставайтесь на связи", rights: "Все права защищены." },
    contact: { title: 'Связаться со мной', firstName: 'Имя', lastName: 'Фамилия', email: 'Email', message: 'Сообщение', submit: 'Отправить', success: 'Сообщение успешно отправлено!', error: 'Ошибка при отправке сообщения. Пожалуйста, попробуйте еще раз.' }
  },
  zh: {
    nav: { home: '首页', about: '历程', vision: '愿景', realisations: '成就', ambassador: '大使', contact: '联系我们' },
    hero: { subtitle: '青年领袖与经济学家', title: "Max Jhonsley Gaspard", desc: "马克思·约翰斯利·加斯帕德是一位年轻的海地领袖、经济学家、演讲者和社会主义活动家，2001年1月19日出生于红湾（阿蒂博尼特）。2026年1月，他作为海地青年参与的新兴人物特别活跃。以下是他经历的关键点：教育和技能：目前居住在中国的多语言者，他利用自己的语言技能，包括普通话，促进中海合作。\n\n政治参与：他将自己定义为一名承诺的政治行动者，公开批评海地当局在教育系统废弃和社会不平等等问题上的做法。当前角色：2026年1月，他被任命为中国图书宇宙大使，使命是促进文学和文化。加斯帕德在海地社交媒体上经常被描述为一位\"决心通过倡议改变海地的年轻领袖\"。", cta1: '他的愿景', cta2: '他的政治路线', badge1: '精通多种语言（普通话）', badge2: '文化大使', readMore: '阅读更多', readLess: '收起' },
    about: { title: '无国界的历程', p1: "马克思于2001年1月19日出生于红湾（Anse-Rouge），他在走向国际舞台的同时，始终深深扎根于海地的土壤。", p2: "他目前常驻中国，利用精通的普通话和经济学专业知识建立战略桥梁。", stats: { origin: '出生地', birth: '出生日期', residence: '现居地', lang: '语言能力' }, cards: { economy: '经济与激进主义', diplomacy: '青年外交', speaker: '励志演讲者' } },
    vision: { title: '他的政治路线', pillars: [{ t: "中海关系拉近", d: "这是他目前演讲的核心。他积极倡导与中国加强双边合作，他认为中国是一个战略伙伴，能够为海地提供传统联盟之外的替代方案。" }, { t: "社会主义和社会改革", d: "他将自己定义为年轻的社会主义领袖，致力于减少社会差异和更好地分配国家财富。" }, { t: "教育作为国家优先事项", d: "他严厉批评现任当局对教育系统的忽视。他的政策基于这样的理念：教育是发展和政治稳定的必要驱动力。" }, { t: "反对传统精英", d: "他将自己定位为对既定政治阶层的批评声音，谴责其长期不稳定和领导人无法满足人民基本需求。" }, { t: "文化外交", d: "通过担任图书大使的角色，他使用文化和文学作为政治影响工具，以恢复海地的国际形象。" }] },
    ambassador: { subtitle: '2026年1月 - 新篇章', title: "图书宇宙驻华大使", desc: "马克思被任命为大使，旨在促进文学和文化交流。", support: "这项使命得到了成千上万年轻读者的支持。" },
    footer: { mission: "作为一名经济学家和坚定的领袖，马克思不懈努力，在海地与世界之间架起桥梁。", contact: "联系方式", location: "中国 / 海地", stayConnected: "保持联系", rights: "保留所有权利。" },
    contact: { title: '联系我', firstName: '名字', lastName: '姓氏', email: '邮箱', message: '消息', submit: '发送', success: '消息发送成功！', error: '发送消息时出错。请重试。' }
  }
};